### ISSUE TITLE
nativeLink happen error.

### ISSUE THREAD

**Issue by GZYangKui** [gluonhq/gluonfx-gradle-plugin#101]
[周五 2月 19 10:38:28 CST 2021][详细] Start process link...
[周五 2月 19 10:38:29 CST 2021][信息] [SUB] /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libgtk-3.so: undefined reference to symbol 'g_module_supported'
[周五 2月 19 10:38:29 CST 2021][信息] [SUB] /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libgmodule-2.0.so: error adding symbols: DSO missing from command line
[周五 2月 19 10:38:29 CST 2021][信息] [SUB] collect2: error: ld returned 1 exit status
[周五 2月 19 10:38:29 CST 2021][详细] Result for link: 1

**Comment by jperedadnr** [comment]
Not enough details (plugin version), but this issue has been fixed with the latest Gluon's GraalVM build.
