### ISSUE TITLE
NativeRun have Exception

### ISSUE THREAD

**Issue by albert-flex** [gluonhq/gluonfx-gradle-plugin#124]
Project : => no module-info.java found
......
[周六 6月 26 22:19:20 CST 2021][信息] [SUB] Caused by: java.lang.UnsatisfiedLinkError: no glib-lite in java.library.path[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:275)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at java.lang.Runtime.loadLibrary0(Runtime.java:830)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at java.lang.System.loadLibrary(System.java:1871)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:163)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.sun.media.jfxmediaimpl.NativeMediaManager.lambda$new$0(NativeMediaManager.java:110)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at java.security.AccessController.doPrivileged(AccessController.java:118)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.sun.media.jfxmediaimpl.NativeMediaManager.<init>(NativeMediaManager.java:107)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.sun.media.jfxmediaimpl.NativeMediaManager$NativeMediaManagerInitializer.<clinit>(NativeMediaManager.java:78)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.sun.media.jfxmediaimpl.NativeMediaManager.getDefaultInstance(NativeMediaManager.java:90)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.sun.media.jfxmedia.MediaManager.canPlayProtocol(MediaManager.java:78)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at com.sun.media.jfxmedia.locator.Locator.<init>(Locator.java:239)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at javafx.scene.media.Media.<init>(Media.java:393)
[周六 6月 26 22:19:20 CST 2021][信息] [SUB]  at albertgame.square.Config.initialize(Config.java:72)
......

project from github.com/albert-factory/albertgame-square.git  branch on develop

Platform: Windows 10
Graalvm: OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
Gradle-Plugin: com.gluonhq.gluonfx-gradle-plugin:1.0.1

**Comment by jperedadnr** [comment]
Native image for Windows doesn't have support yet for Media or Web.
