### ISSUE TITLE
mainClassName is depracated

### ISSUE THREAD

**Issue by SR-Lut3t1um** [gluonhq/gluonfx-gradle-plugin#127]
When setting the main class with the currently supposed way like this: 
`mainClass.set("<pathToMainClass>")`
gluon is throwing the following error: 
```
Execution failed for task ':nativeCompile'.
> Main class name is required
```
however when using the now deprecated way like this: 

```
@kotlin.Suppress("Deprecated") // required for gluon
mainClassName = "<pathToMainClass>" 
```
everything works just like expected.

**Comment by st4s1k** [comment]
Seems like gluon gradle plugin is "deprecated"
