### ISSUE TITLE
Failed ./gradlew nativePackage on iOS

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/gluonfx-gradle-plugin#142]
While running the command ./gradlew Package on the mac, I get this error: 

Mac:gfx_app Utente$ ./gradlew -- stacktrace Package
> Configure project :
Project : => no module-info.java found
FAILURE: Build failed with an exception.
* What went wrong:
Task 'stacktrace' not found in root project 'gfx_app'.
* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 1s

what can it depend on?

**Comment by jperedadnr** [comment]
`./gradlew -- stacktrace Package` is a wrong command, as the error says:
> Task 'stacktrace' not found in root project 'gfx_app'.

Probably you want:
```
./gradlew --stacktrace nativePackage
```

**Comment by websystemtechnology** [comment]
> `./gradlew -- stacktrace Package` is a wrong command, as the error says:
> 
> > Task 'stacktrace' not found in root project 'gfx_app'.
> 
> Probably you want:
> 
> ```
> ./gradlew --stacktrace nativePackage
> ```

Yes, the command is the nativePackage, and the error is the one described and in the first comment. The error is due to copy and paste while opening the issue.
