### ISSUE TITLE
DatePicker dialog doesn't work on iPhone 12 or greater

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/gluonfx-gradle-plugin#156]
With iPhone 12 or higher, the DatePicker window blocks its execution when the showAndWait method is called, without showing exceptions and without opening its dialog. In addition, it is no longer possible to go back but you must necessarily close the app.
https://docs.gluonhq.com/charm/javadoc/6.0.6/com.gluonhq.charm.glisten/com/gluonhq/charm/glisten/control/DatePicker.html

I have attached the log of the run made on an iPhone 12. By clicking on the central button that should open the calendar for choosing the date, the app freezes and I can do nothing but close it.
[Run_Iphone12.txt](https://github.com/gluonhq/gluonfx-gradle-plugin/files/9133453/Run_Iphone12.txt)

this is the example project:
[project_test.zip](https://github.com/gluonhq/gluonfx-gradle-plugin/files/9133475/project_test.zip)

**Comment by jperedadnr** [comment]
I don't have iPhone 12 or higher to test. Do you mean that the same app works fine on iPhone 11 or lower?

**Comment by websystemtechnology** [comment]
Yes, the problem starts with iPhone 12 and later

**Comment by websystemtechnology** [comment]
Is the com.gluonhq.charm.glisten.control.DatePicker component to be used only in a Dialog or is there a way to use it as a node in a view?
Is DatePicker the only component to display a calendar and select a date or is there another component?

**Comment by jperedadnr** [comment]
FYI: There was a similar [issue](https://github.com/gluonhq/attach/issues/322) reported on Attach/BarcodeScanner service and we have identified the [problem](https://github.com/gluonhq/attach/issues/322#issuecomment-1234442216).

All classes that extend from GluonMobile's `Dialog` use `enterNestedEventLoop`, so that needs to be fixed.
