### ISSUE TITLE
nativeRunAgent Task failing

### ISSUE THREAD

**Issue by UtilFunction** [gluonhq/gluonfx-gradle-plugin#182]
**Problem:**
Running `./gradlew nativeRunAgent` results in an error: 
`Error creating Substrate Dispatcher: java.lang.NullPointerException: Main class name is required`. 

Main class already defined in the `application` block
```
application {
    mainClass = 'fx.App'
}
```

Adding `mainClassName = 'fx.App'` results in an error as well: 
`RunAgent failure: org.gradle.api.internal.provider.AbstractProperty$PropertyQueryException: Failed to calculate the value of task ':app:run' property 'javaLauncher'.`

[Sample Project](https://github.com/UtilFunction/gluonsample)

Environment:
- Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15)
- Gradle 8.4-rc-1

**Comment by SabujXi** [comment]
This gralde plugin took two days and nights of sleep away. Application is fine, running fine but no native build, compile link, agent things were working.

The biggest pain: NO useful error message.

After hours and hours of debugging and sleepless night, dizzy days here is the result:
The gradle plugin from gluon is "broken".

Solution: use the maven plugin.

**Comment by UtilFunction** [comment]
> Solution: use the maven plugin.

Agree. It's not only the gluonfx plugin but also the javafx gradle plugin that seems to be doing werid things as [described here](https://github.com/openjfx/javafx-gradle-plugin/issues/156).
